POST http://localhost:8888/.netlify/functions/imageFromHtml HTTP/1.1
Content-Type: application/json

{
  "base": { 
    "id": "appls7XVxwxuDkhMg" 
  },
  "webhook": { 
    "id": "achFf8AHIhqRPIGbG" 
  },
  "timestamp": "2023-02-28T03:47:02.690Z"
}